version: "3.4"
services:
  civicrm:
    image: michaelmcandrew/civicrm-backdrop
    hostname: $PROJECT_NAME
    environment:
      - APACHE_RUN_USER=civicrm
      - PROJECT_NAME
      - BASE_URL
      - CIVICRM_DB_NAME
      - CIVICRM_DB_USER
      - CIVICRM_DB_PASS
      - CIVICRM_DB_HOST
      - CIVICRM_DB_PORT
      - DEBUG=ON
      - BACKDROP_DB_NAME
      - BACKDROP_DB_USER
      - BACKDROP_DB_PASS
      - BACKDROP_DB_HOST
      - BACKDROP_DB_PORT
      - MYSQL_ROOT_PASSWORD
      - SMTP_HOST
      - SMTP_MAILDOMAIN
    ports:
      - NNNN:80
    volumes:
      - ./src:/var/www/html
      - files:/var/www/html/files
      - ./state:/state
      - ./.bash_history:/home/civicrm/.bash_history
    restart: always
  mysql:
    image: michaelmcandrew/civicrm-mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    restart: always
  maildev:
    image: djfarrelly/maildev
    restart: always
    ports:
      - NNNN:80
volumes:
  files:
  mysql:
