version: "3.4"
services:
  civicrm:
    image: michaelmcandrew/civicrm:drupal
    hostname: $PROJECT_NAME
    environment:
      - APACHE_RUN_USER=civicrm
      - PROJECT_NAME
      - BASE_URL
      - CIVICRM_DB_NAME
      - CIVICRM_DB_USER
      - CIVICRM_DB_PASS
      - CIVICRM_DB_HOST
      - CIVICRM_DB_PORT
      - DRUPAL_DB_NAME
      - DRUPAL_DB_USER
      - DRUPAL_DB_PASS
      - DRUPAL_DB_HOST
      - DRUPAL_DB_PORT
    ports:
      - NNNN:80
    volumes:
      - files:/var/www/html/sites/default/files
      - ./state:/state
      - ./.bash_history:/home/civicrm/.bash_history
    restart: always
volumes:
  files:
